version: '3.8'

services:
  wog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - ./Scores.txt:/Scores.txt
    image: liransilver/wog:latest